<?php
$z[0]=Array("source","",148,163);
$z[0][4]=array();
$z[1]=Array("arcurl","",186,201);
$z[1][4]=array();
$z[2]=Array("title","",203,217);
$z[2][4]=array();
$z[3]=Array("pubdate","",276,323);
$z[3][4]=array();
$z[3][4]['function']="MyDate('d H:i',@me)";
$z[4]=Array("pubdate","",357,404);
$z[4][4]=array();
$z[4][4]['function']="MyDate('m H:i',@me)";
$z[5]=Array("pubdate","",472,519);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y H:i',@me)";
$z[6]=Array("arcurl","",584,599);
$z[6][4]=array();
$z[7]=Array("picname","",636,652);
$z[7][4]=array();

?>