<?php
$z[0]=Array("picname","",81,97);
$z[0][4]=array();
$z[1]=Array("arcurl","",120,135);
$z[1][4]=array();
$z[2]=Array("arcurl","",328,343);
$z[2][4]=array();
$z[3]=Array("title","",399,413);
$z[3][4]=array();
$z[4]=Array("pubdate","",561,612);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("shorttitle","",658,677);
$z[5][4]=array();
$z[6]=Array("arcurl","",714,729);
$z[6][4]=array();

?>