<?php
$z[0]=Array("softrank","",76,121);
$z[0][4]=array();
$z[0][4]['function']="GetRankStar(@me)";
$z[1]=Array("source","",184,199);
$z[1][4]=array();
$z[2]=Array("arcurl","",222,237);
$z[2][4]=array();
$z[3]=Array("title","",239,253);
$z[3][4]=array();
$z[4]=Array("pubdate","",312,359);
$z[4][4]=array();
$z[4][4]['function']="MyDate('d H:i',@me)";
$z[5]=Array("pubdate","",393,437);
$z[5][4]=array();
$z[5][4]['function']="MyDate('m ',@me)";
$z[6]=Array("pubdate","",505,552);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y H:i',@me)";
$z[7]=Array("arcurl","",617,632);
$z[7][4]=array();
$z[8]=Array("picname","",669,685);
$z[8][4]=array();
$z[9]=Array("shorttitle","",692,711);
$z[9][4]=array();

?>