<section class="article-item zoomIn article">
								<div class="fc-flag">[field:softrank function='GetRankStar(@me)'/]</div>
								<h5 class="title">       <span class="fc-blue">[field:source/]</span>       <a href="[field:arcurl/]">[field:title/]</a>   </h5>
								<div class="time"> <span class="day">[field:pubdate function="MyDate('d H:i',@me)"/]</span> <span class="month fs-18">[field:pubdate function="MyDate('m ',@me)"/]<span class="fs-14">月</span></span> <span class="year fs-18 ml10">[field:pubdate function="MyDate('Y H:i',@me)"/]</span> </div>
								<div class="content">
									<a href="[field:arcurl/]" class="cover img-light"> <img src="[field:picname/]"> </a>[field:shorttitle/]</div>
								<aside class="f-oh footer">
									<div class="f-fl tags"> <span class="fa fa-tags fs-16"></span>
										<a class="tag">JavaScript</a>
									</div>
									<div class="f-fr"> <span class="read">               <i class="fa fa-eye fs-16"></i>               <i class="num">228</i>           </span> <span class="ml20">               <i class="fa fa-comments fs-16"></i>               <a href="javascript:void(0)" class="num fc-grey">3</a>           </span> </div>
								</aside>
							</section>