<div class="single-news">
									<div class="news-head">
										<img src="[field:picname/]">
										<a href="[field:arcurl/]" class="link"><i class="fa fa-link"></i></a>
									</div>
									<div class="news-content">
										<h4 class="layui-elip">
                                                <a href="[field:arcurl/]">
                                                    [field:title/]
                                                </a>
                                            </h4>
										<div class="date">
											[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]
										</div>
										<p>
											{dede:field.description}
										</p>
										<a href="[field:arcurl/]" class="btn">
											阅读更多
										</a>
									</div>
								</div>