<?php
$z[0]=Array("arcurl","",191,206);
$z[0][4]=array();
$z[1]=Array("pubdate","",286,333);
$z[1][4]=array();
$z[1][4]['function']="MyDate('d H:i',@me)";
$z[2]=Array("pubdate","",367,414);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m H:i',@me)";
$z[3]=Array("pubdate","",482,529);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y H:i',@me)";
$z[4]=Array("arcurl","",594,609);
$z[4][4]=array();
$z[5]=Array("picname","",646,662);
$z[5][4]=array();
$z[6]=Array("arcurl","",753,768);
$z[6][4]=array();

?>