<div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp animated" data-wow-delay=".2s" style="padding: 0px 10px; visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
								<div class="single-news">
									<div class="news-head">
										<img src="[field:picname/]">
										<a href="https://www.yanshisan.cn/Blog/Read/20" class="link"><i class="fa fa-link"></i></a>
									</div>
									<div class="news-content">
										<h4 class="layui-elip">
                                                <a href="https://www.yanshisan.cn/Blog/Read/20">
                                                    我的第一个C/S项目
                                                </a>
                                            </h4>
										<div class="date">
											2019年09月20日
										</div>
										<p>

											FastReport.Net是一款适用于Windows Forms, ASP.NET和MVC框架的功能齐全的报表分析解决方案，支持.Net Framework 2.0到4.x。
										</p>
										<a href="https://www.yanshisan.cn/Blog/Read/20" class="btn">
											阅读更多
										</a>
									</div>
								</div>
							</div>
							<div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp animated" data-wow-delay=".4s" style="padding: 0px 10px; visibility: visible; animation-delay: 0.4s; animation-name: fadeInUp;">
								<div class="single-news">
									<div class="news-head">
										<img src="%E7%87%95%E5%8D%81%E4%B8%89%C2%B7%E4%B8%80%E4%B8%AA%E4%BA%BA%E7%9A%84%E6%B1%9F%E6%B9%96_files/201963164541362.jpg">
										<a href="https://www.yanshisan.cn/Blog/Read/19" class="link"><i class="fa fa-link"></i></a>
									</div>
									<div class="news-content">
										<h4 class="layui-elip">
                                                <a href="https://www.yanshisan.cn/Blog/Read/19">
                                                    MUI上拉加载和下拉刷新出现双滚动条BUG解决办法
                                                </a>
                                            </h4>
										<div class="date">
											2019年07月03日
										</div>
										<p>
											滚动组件与刷新容器之双滚动条解决方案
										</p>
										<a href="https://www.yanshisan.cn/Blog/Read/19" class="btn">
											阅读更多
										</a>
									</div>
								</div>
							</div>
						</div>