<?php
$z[0]=Array("picname","",254,270);
$z[0][4]=array();
$z[1]=Array("arcurl","",293,308);
$z[1][4]=array();
$z[2]=Array("arcurl","",501,516);
$z[2][4]=array();
$z[3]=Array("title","",572,586);
$z[3][4]=array();
$z[4]=Array("pubdate","",734,785);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("shorttitle","",831,850);
$z[5][4]=array();
$z[6]=Array("arcurl","",887,902);
$z[6][4]=array();

?>