<div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp animated" data-wow-delay=".2s" style="padding: 0px 10px; visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
								<div class="single-news">
									<div class="news-head">
										<img src="[field:picname/]">
										<a href="https://www.yanshisan.cn/Blog/Read/20" class="link"><i class="fa fa-link"></i></a>
									</div>
									<div class="news-content">
										<h4 class="layui-elip">
                                                <a href="https://www.yanshisan.cn/Blog/Read/20">
                                                    我的第一个C/S项目
                                                </a>
                                            </h4>
										<div class="date">
											2019年09月20日
										</div>
										<p>

											FastReport.Net是一款适用于Windows Forms, ASP.NET和MVC框架的功能齐全的报表分析解决方案，支持.Net Framework 2.0到4.x。
										</p>
										<a href="https://www.yanshisan.cn/Blog/Read/20" class="btn">
											阅读更多
										</a>
									</div>
								</div>
							</div>
							
						</div>