<?php
$z[0]=Array("title","",76,90);
$z[0][4]=array();
$z[1]=Array("source","",153,168);
$z[1][4]=array();
$z[2]=Array("arcurl","",191,206);
$z[2][4]=array();
$z[3]=Array("title","",208,222);
$z[3][4]=array();
$z[4]=Array("pubdate","",281,328);
$z[4][4]=array();
$z[4][4]['function']="MyDate('d H:i',@me)";
$z[5]=Array("pubdate","",362,406);
$z[5][4]=array();
$z[5][4]['function']="MyDate('m ',@me)";
$z[6]=Array("pubdate","",474,521);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y H:i',@me)";
$z[7]=Array("arcurl","",586,601);
$z[7][4]=array();
$z[8]=Array("picname","",638,654);
$z[8][4]=array();
$z[9]=Array("shorttitle","",661,680);
$z[9][4]=array();

?>