<?php
$z[0]=Array("global","",358,384);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",418,448);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("type","\r\n									<a href=\"[field:typelink/]\" class=\"btn layui-btn layui-btn-normal\">About Me</a>\r\n									",493,628);
$z[2][4]=array();
$z[2][4]['typeid']="5";
$z[3]=Array("flink","\r\n									<li class=\"active\" >\r\n									  [field:link /] \r\n									</li>\r\n									 ",849,995);
$z[3][4]=array();
$z[3][4]['titlelen']="20";
$z[3][4]['row']="6";
$z[3][4]['type']="text";
$z[4]=Array("global","",1243,1266);
$z[4][4]=array();
$z[4][4]['name']="cfg_site";
$z[5]=Array("global","",1310,1331);
$z[5][4]=array();
$z[5][4]['name']="cfg_QQ";
$z[6]=Array("global","",1382,1410);
$z[6][4]=array();
$z[6][4]['name']="cfg_QQmailbox";
$z[7]=Array("global","",1672,1696);
$z[7][4]=array();
$z[7][4]['name']="cfg_beian";

?>